version: "3.8"

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: ttt_user
      POSTGRES_PASSWORD: ttt_password
      POSTGRES_DB: ttt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: my_pgweb
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://ttt_user:ttt_password@postgres_db:5432/ttt_db?sslmode=disable
    depends_on:
      - postgres_db

  react_frontend:
    image: node:20-alpine
    container_name: my_react_frontend
    restart: always
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev -- --host"

  spring_backend:
    image: maven:3.9-eclipse-temurin-17-alpine
    container_name: my_spring_backend
    restart: always
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    environment:
      - MAVEN_OPTS=-Djava.security.egd=file:/dev/./urandom
    command: mvn spring-boot:run
    depends_on:
      - postgres_db

volumes:
  postgres_data:
  pgadmin_data:
