spring.datasource.url=jdbc:postgresql://postgres_db:5432/ttt_db
spring.datasource.username=ttt_user
spring.datasource.password=ttt_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Das zwingt Hibernate, den korrekten Dialekt ohne Abfrage zu nutzen
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Das sorgt dafür, dass die Tabellen automatisch generiert werden
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Verhindert, dass die App sofort abstürzt, wenn Postgres 2 Sekunden zum Starten braucht
spring.datasource.hikari.initialization-fail-timeout=0
